name: build-and-check

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt || true

      - name: Lint
        run: |
          pip install ruff black
          ruff check .
          black --check .

      - name: Syntax check
        run: python -m compileall .

      - name: Run tests
        run: pytest -q -W error::DeprecationWarning

      - name: Smoke test /health
        run: |
          python - << 'PY'
          import threading, time, requests
          from api import app
          from werkzeug.serving import make_server

          class ServerThread(threading.Thread):
              def __init__(self, app):
                  threading.Thread.__init__(self)
                  self.srv = make_server('127.0.0.1', 5001, app)
                  self.ctx = app.app_context()
                  self.ctx.push()

              def run(self):
                  self.srv.serve_forever()

              def shutdown(self):
                  self.srv.shutdown()

          t = ServerThread(app); t.start(); time.sleep(0.5)
          r = requests.get("http://127.0.0.1:5001/health")
          assert r.status_code == 200, r.text
          t.shutdown(); t.join()
          PY
